use_frameworks!

platform :ios, '9.0'

target 'SDWebImageMockPlugin_Example' do
  pod 'SDWebImageMockPlugin', :path => '../'

  target 'SDWebImageMockPlugin_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
