use_frameworks!

platform :ios, '13.0'

target 'SDWebImageMockPlugin_Example' do
  pod 'SDWebImageMockPlugin', :path => '../'

  pod 'SDWebImage', '~> 5.0'
  pod 'SwiftLint', '~> 0.46.0'

  target 'SDWebImageMockPlugin_Tests' do
    inherit! :search_paths

    pod 'SnapshotTesting', '~> 1.9.0'
  end
end
